name: build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      
      - name: Setup Nuget.exe
        uses: nuget/setup-nuget@master
      
      - name: Restore Nuget packages
        run: nuget restore HandyWinGet-GUI.sln

      - name: Setup .NET Core
        uses: actions/setup-dotnet@master
  
      - name: Build Core_31
        run: dotnet build HandyWinGet-GUI/HandyWinGet-GUI.csproj --configuration Release
